### ISSUE TITLE
Python script to convert xls to csv

### ISSUE THREAD

**Issue by pontikos** [plagnollab/DNASeq_pipeline#27]
@APLevine could you please share you script to translate the spreadsheets in:

> /goon2/project99/IBDAJE_raw/Macrogen/150115_ElenaSchiff_1411KHP-0031_Exome/

to csv?

**Comment by APLevine** [comment]
Have a look here in this folder:
/cluster/project8/IBDAJE/Macrogen_more_Excel

Look at submit.sh

You will need to install Pip and then xlsx2csv (https://github.com/dilshod/xlsx2csv)

----
APL

**Comment by pontikos** [comment]
https://gist.github.com/pontikos/dde7f68bc9baffb5ecd3
