### ISSUE TITLE
ExAC/ESP

### ISSUE THREAD

**Issue by APLevine** [plagnollab/DNASeq_pipeline#31]
Nikolas, I just saw that this:

https://github.com/plagnollab/DNASeq_pipeline/blob/master/annotation/processVEP.py#L13

**Comment by vplagnol** [comment]
Well spotted.


On Fri, Feb 13, 2015 at 10:39 AM, APLevine <notifications@github.com> wrote:

> Nikolas, I just saw that this:
>
>
> https://github.com/plagnollab/DNASeq_pipeline/blob/master/annotation/processVEP.py#L13
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plagnollab/DNASeq_pipeline/issues/31>.
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/
